### ISSUE TITLE
Config from website

### ISSUE THREAD

**Issue by CitralFlo** [EternalCodeTeam/website#46]
**Issue:**
I don't really know what I can type in certain cofig options. Sometimes I would like to select super specyfic variables, e.g purpur stairs blocks, and I always make a mistake in spelling

**My solution:**
Make a website that writes down the code for You. With each choice the User will be getting dropdown list of blocks / iteractions / choices. Devs can add specyfic vid that shows the result of my config: enable effects -> camera in the fight gets effects.

**Alternative solution:**
Surfing through the web by checking lists from bukkit that developers linked in their cofig instructions.

**Additional info:**
User gets to download the config file, or gets to copy the code for the file.

Me rn:
```
d-_-b
```

**Comment by vLuckyyy** [comment]
I don't understand what these issues have to do with the website.

**Comment by CitralFlo** [comment]
> I don't understand what these issues have to do with the website.

pessimistic as always

**Comment by vLuckyyy** [comment]
> > I don't understand what these issues have to do with the website.
> 
> pessimistic as always

The issue should be directly related to the website. I don't understand what you mean and how these changes would contribute to the improvement/development of the website. Please elaborate on what you mean. Currently, it seems as if it is more closely related to [Docs](https://github.com/eternalcodeteam/docs) or [EternalCombat](https://github.com/eternalcodeteam/eternalcombat).

**Comment by CitralFlo** [comment]
> > > I don't understand what these issues have to do with the website.
> > 
> > 
> > pessimistic as always
> 
> The issue should be directly related to the website. I don't understand what you mean and how these changes would contribute to the improvement/development of the website. Please elaborate on what you mean. Currently, it seems as if it is more closely related to [Docs](https://github.com/eternalcodeteam/docs) or [EternalCombat](https://github.com/eternalcodeteam/eternalcombat).

I was thinking about using our website and developing skills in file extraction / animation / making guis in the way to help commuinity, because prblly most common problem in our projects is incorrect config editing.

**Comment by Rollczi** [comment]
I think it is a great idea, but there is no repository related to that. We can create a new repository for that.
